// Protocol generation — pure transforms behind `npm run gen:protocol`
// (scripts/gen-protocol.mjs at the repo root).
//
// The CANONICAL protocol is the PUBLISHED DOC PAGE, `docs/reference/agent-protocol.md`
// (and `docs/guide/authoring.md` for the authoring palette): written by hand, reviewed
// with the loop like any other page. Every other copy is GENERATED from it, so they
// can never drift apart:
//
//   docs/reference/agent-protocol.md ─┬─(+ plugin overlay)─→ skills/notabene/SKILL.md
//                                     └─(+ version banner)─→ packages/renderer/protocol.md
//                                                            (npm + <store>/protocol.md)
//
// The page's site frontmatter is stripped (the skill brings its own), then the text is
// split at BODY_MARKER: everything before it is the audience's front-door (how to run
// the CLI here, what to do when notabene isn't set up), everything after is the shared
// body. An overlay is a template whose `{{body}}` receives it — so per-audience
// differences stay in ONE place instead of being sprinkled through the protocol as
// conditional markers.
//
// Raw-Node importable (bin/ and scripts/ use it outside Vite): no imports at all.

/** Protocol revision, bumped BY HAND when the spec changes materially. Deliberately
 *  NOT the package version: the generated files are committed and diff-gated in CI, so
 *  interpolating a version that moves on every release would break the gate on every
 *  release commit. Consumers see it in the banner of `<store>/protocol.md`. */
export const PROTOCOL_VERSION = 3;

/** Store schema this revision of the protocol describes (comment-types.ts SCHEMA_VERSION). */
export const PROTOCOL_STORE_SCHEMA = 3;

/** Splits a spec's front-door from its shared body. */
export const BODY_MARKER = "<!-- nb:body -->";

/** Placeholder an overlay template uses to receive the shared body. */
export const BODY_PLACEHOLDER = "{{body}}";

const GENERATOR = "scripts/gen-protocol.mjs";

/** Drop a leading YAML frontmatter block (the doc page's site metadata — a skill and
 *  the packaged protocol each bring their own header). */
export function stripFrontmatter(text) {
  return text.replace(/^---\r?\n[\s\S]*?\r?\n---[ \t]*\r?\n/, "").trimStart();
}

/** Drop the HTML comment(s) a canonical page opens with — "edit me here, run
 *  gen:protocol" is an instruction to THIS repo's editors, meaningless (and
 *  misleading) once the text is sitting in a consumer's store. */
export function stripLeadingComments(text) {
  let out = text.trimStart();
  while (out.startsWith("<!--")) {
    const end = out.indexOf("-->");
    if (end === -1) break;
    out = out.slice(end + 3).trimStart();
  }
  return out;
}

/** A canonical page reduced to the text every copy shares. */
export function specSource(text) {
  return stripLeadingComments(stripFrontmatter(text));
}

/** `{ header, body }` — throws if the spec has no BODY_MARKER (a silent miss would
 *  ship the neutral front-door inside the Claude skill). */
export function splitSpec(text) {
  const i = text.indexOf(BODY_MARKER);
  if (i === -1) throw new Error(`protocol spec: missing ${BODY_MARKER}`);
  return {
    header: text.slice(0, i).trimEnd(),
    body: text.slice(i + BODY_MARKER.length).trimStart(),
  };
}

/** The whole spec as one document (front-door + body), frontmatter and marker gone. */
export function joinSpec(text) {
  const { header, body } = splitSpec(specSource(text));
  return `${header}\n\n${body}`;
}

/** "generated, do not edit" line for outputs whose provenance is all that matters. */
export function generatedBanner(sources) {
  return `<!-- Generated from ${sources.join(" + ")} by ${GENERATOR} — do not edit. -->`;
}

/** Banner for the DISTRIBUTED protocol (npm package + `<store>/protocol.md`). Its
 *  first token is the sentinel `init` uses to tell "a file notabene generated" from
 *  "a file the user wrote" before ever overwriting it. */
export function protocolBanner() {
  return (
    `<!-- notabene agent protocol v${PROTOCOL_VERSION} · store schemaVersion ` +
    `${PROTOCOL_STORE_SCHEMA} · generated — do not edit -->`
  );
}

const PROTOCOL_BANNER_RE = /^<!--\s*notabene agent protocol v(\d+)\b/;

/** Was this text generated by us? (Only then may `init` overwrite it.) */
export function isGeneratedProtocol(text) {
  return PROTOCOL_BANNER_RE.test(String(text ?? "").trimStart());
}

/** Protocol revision of a generated copy, or null when it isn't one of ours. */
export function parseProtocolVersion(text) {
  const m = PROTOCOL_BANNER_RE.exec(String(text ?? "").trimStart());
  return m ? Number(m[1]) : null;
}

/** Insert `block` right after a leading YAML frontmatter (a banner must never
 *  precede `---`, or the frontmatter stops being frontmatter). */
export function insertAfterFrontmatter(text, block) {
  const m = /^---\r?\n[\s\S]*?\r?\n---[ \t]*\r?\n/.exec(text);
  if (!m) return `${block}\n\n${text}`;
  return `${m[0]}\n${block}\n${text.slice(m[0].length)}`;
}

/** Insert `block` right after the first `# H1` (falls back to prepending). */
export function insertAfterH1(text, block) {
  const m = /^#[ \t]+[^\n]*\n/m.exec(text);
  if (!m) return `${block}\n\n${text}`;
  const at = m.index + m[0].length;
  return `${text.slice(0, at)}\n${block}\n${text.slice(at)}`;
}

/** Claude Code skill = overlay template (frontmatter + client rules) + shared body. */
export function renderSkill({ overlay, spec, sources }) {
  if (!overlay.includes(BODY_PLACEHOLDER)) {
    throw new Error(`overlay: missing ${BODY_PLACEHOLDER}`);
  }
  const { body } = splitSpec(specSource(spec));
  // Function replacer, NOT a string: the spec is prose full of `$` (`$…$` renders
  // literally, shell snippets) and String.replace would read `$&`/`` $` ``/`$'` as
  // substitution patterns — splicing the overlay back into the middle of the body.
  const merged = overlay.replace(BODY_PLACEHOLDER, () => body.trimEnd());
  return `${insertAfterFrontmatter(merged, generatedBanner(sources)).trimEnd()}\n`;
}

/** The distributed protocol: the neutral document, versioned banner on top. */
export function renderProtocol({ spec }) {
  return `${protocolBanner()}\n\n${joinSpec(spec).trimEnd()}\n`;
}
